import json

# (number, name, arabicName, englishTranslation, ayahCount, revelationType, juz[])
rows = [
(1,"Al-Fatihah","الفاتحة","The Opening",7,"meccan",[1]),
(2,"Al-Baqarah","البقرة","The Cow",286,"medinan",[1,2,3]),
(3,"Aal-Imran","آل عمران","The Family of Imran",200,"medinan",[3,4]),
(4,"An-Nisa","النساء","The Women",176,"medinan",[4,5,6]),
(5,"Al-Ma'idah","المائدة","The Table Spread",120,"medinan",[6,7]),
(6,"Al-An'am","الأنعام","The Cattle",165,"meccan",[7,8]),
(7,"Al-A'raf","الأعراف","The Heights",206,"meccan",[8,9]),
(8,"Al-Anfal","الأنفال","The Spoils of War",75,"medinan",[9,10]),
(9,"At-Tawbah","التوبة","The Repentance",129,"medinan",[10,11]),
(10,"Yunus","يونس","Jonah",109,"meccan",[11]),
(11,"Hud","هود","Hud",123,"meccan",[12]),
(12,"Yusuf","يوسف","Joseph",111,"meccan",[12,13]),
(13,"Ar-Ra'd","الرعد","The Thunder",43,"medinan",[13]),
(14,"Ibrahim","إبراهيم","Abraham",52,"meccan",[13]),
(15,"Al-Hijr","الحجر","The Rocky Tract",99,"meccan",[14]),
(16,"An-Nahl","النحل","The Bee",128,"meccan",[14]),
(17,"Al-Isra","الإسراء","The Night Journey",111,"meccan",[15]),
(18,"Al-Kahf","الكهف","The Cave",110,"meccan",[15,16]),
(19,"Maryam","مريم","Mary",98,"meccan",[16]),
(20,"Ta-Ha","طه","Ta-Ha",135,"meccan",[16]),
(21,"Al-Anbiya","الأنبياء","The Prophets",112,"meccan",[17]),
(22,"Al-Hajj","الحج","The Pilgrimage",78,"medinan",[17]),
(23,"Al-Mu'minun","المؤمنون","The Believers",118,"meccan",[18]),
(24,"An-Nur","النور","The Light",64,"medinan",[18]),
(25,"Al-Furqan","الفرقان","The Criterion",77,"meccan",[18,19]),
(26,"Ash-Shu'ara","الشعراء","The Poets",227,"meccan",[19]),
(27,"An-Naml","النمل","The Ant",93,"meccan",[19,20]),
(28,"Al-Qasas","القصص","The Stories",88,"meccan",[20]),
(29,"Al-Ankabut","العنكبوت","The Spider",69,"meccan",[20,21]),
(30,"Ar-Rum","الروم","The Romans",60,"meccan",[21]),
(31,"Luqman","لقمان","Luqman",34,"meccan",[21]),
(32,"As-Sajdah","السجدة","The Prostration",30,"meccan",[21]),
(33,"Al-Ahzab","الأحزاب","The Combined Forces",73,"medinan",[21,22]),
(34,"Saba","سبأ","Sheba",54,"meccan",[22]),
(35,"Fatir","فاطر","Originator",45,"meccan",[22]),
(36,"Ya-Sin","يس","Ya-Sin",83,"meccan",[22,23]),
(37,"As-Saffat","الصافات","Those Who Set The Ranks",182,"meccan",[23]),
(38,"Sad","ص","The Letter Sad",88,"meccan",[23]),
(39,"Az-Zumar","الزمر","The Troops",75,"meccan",[23,24]),
(40,"Ghafir","غافر","The Forgiver",85,"meccan",[24]),
(41,"Fussilat","فصلت","Explained in Detail",54,"meccan",[24,25]),
(42,"Ash-Shura","الشورى","The Consultation",53,"meccan",[25]),
(43,"Az-Zukhruf","الزخرف","The Ornaments of Gold",89,"meccan",[25]),
(44,"Ad-Dukhan","الدخان","The Smoke",59,"meccan",[25]),
(45,"Al-Jathiyah","الجاثية","The Crouching",37,"meccan",[25]),
(46,"Al-Ahqaf","الأحقاف","The Wind-Curved Sandhills",35,"meccan",[26]),
(47,"Muhammad","محمد","Muhammad",38,"medinan",[26]),
(48,"Al-Fath","الفتح","The Victory",29,"medinan",[26]),
(49,"Al-Hujurat","الحجرات","The Rooms",18,"medinan",[26]),
(50,"Qaf","ق","The Letter Qaf",45,"meccan",[26]),
(51,"Adh-Dhariyat","الذاريات","The Winnowing Winds",60,"meccan",[26,27]),
(52,"At-Tur","الطور","The Mount",49,"meccan",[27]),
(53,"An-Najm","النجم","The Star",62,"meccan",[27]),
(54,"Al-Qamar","القمر","The Moon",55,"meccan",[27]),
(55,"Ar-Rahman","الرحمن","The Beneficent",78,"medinan",[27]),
(56,"Al-Waqi'ah","الواقعة","The Inevitable",96,"meccan",[27]),
(57,"Al-Hadid","الحديد","The Iron",29,"medinan",[27]),
(58,"Al-Mujadila","المجادلة","The Pleading Woman",22,"medinan",[28]),
(59,"Al-Hashr","الحشر","The Exile",24,"medinan",[28]),
(60,"Al-Mumtahanah","الممتحنة","She That Is To Be Examined",13,"medinan",[28]),
(61,"As-Saff","الصف","The Ranks",14,"medinan",[28]),
(62,"Al-Jumu'ah","الجمعة","The Congregation, Friday",11,"medinan",[28]),
(63,"Al-Munafiqun","المنافقون","The Hypocrites",11,"medinan",[28]),
(64,"At-Taghabun","التغابن","The Mutual Disillusion",18,"medinan",[28]),
(65,"At-Talaq","الطلاق","The Divorce",12,"medinan",[28]),
(66,"At-Tahrim","التحريم","The Prohibition",12,"medinan",[28]),
(67,"Al-Mulk","الملك","The Sovereignty",30,"meccan",[29]),
(68,"Al-Qalam","القلم","The Pen",52,"meccan",[29]),
(69,"Al-Haqqah","الحاقة","The Reality",52,"meccan",[29]),
(70,"Al-Ma'arij","المعارج","The Ascending Stairways",44,"meccan",[29]),
(71,"Nuh","نوح","Noah",28,"meccan",[29]),
(72,"Al-Jinn","الجن","The Jinn",28,"meccan",[29]),
(73,"Al-Muzzammil","المزمل","The Enshrouded One",20,"meccan",[29]),
(74,"Al-Muddaththir","المدثر","The Cloaked One",56,"meccan",[29]),
(75,"Al-Qiyamah","القيامة","The Resurrection",40,"meccan",[29]),
(76,"Al-Insan","الإنسان","Man",31,"medinan",[29]),
(77,"Al-Mursalat","المرسلات","The Emissaries",50,"meccan",[29]),
(78,"An-Naba","النبأ","The Tidings",40,"meccan",[30]),
(79,"An-Nazi'at","النازعات","Those Who Drag Forth",46,"meccan",[30]),
(80,"Abasa","عبس","He Frowned",42,"meccan",[30]),
(81,"At-Takwir","التكوير","The Overthrowing",29,"meccan",[30]),
(82,"Al-Infitar","الإنفطار","The Cleaving",19,"meccan",[30]),
(83,"Al-Mutaffifin","المطففين","The Defrauding",36,"meccan",[30]),
(84,"Al-Inshiqaq","الإنشقاق","The Sundering",25,"meccan",[30]),
(85,"Al-Buruj","البروج","The Mansions of the Stars",22,"meccan",[30]),
(86,"At-Tariq","الطارق","The Nightcomer",17,"meccan",[30]),
(87,"Al-A'la","الأعلى","The Most High",19,"meccan",[30]),
(88,"Al-Ghashiyah","الغاشية","The Overwhelming",26,"meccan",[30]),
(89,"Al-Fajr","الفجر","The Dawn",30,"meccan",[30]),
(90,"Al-Balad","البلد","The City",20,"meccan",[30]),
(91,"Ash-Shams","الشمس","The Sun",15,"meccan",[30]),
(92,"Al-Layl","الليل","The Night",21,"meccan",[30]),
(93,"Ad-Duha","الضحى","The Morning Hours",11,"meccan",[30]),
(94,"Ash-Sharh","الشرح","The Relief",8,"meccan",[30]),
(95,"At-Tin","التين","The Fig",8,"meccan",[30]),
(96,"Al-'Alaq","العلق","The Clot",19,"meccan",[30]),
(97,"Al-Qadr","القدر","The Power",5,"meccan",[30]),
(98,"Al-Bayyinah","البينة","The Clear Proof",8,"medinan",[30]),
(99,"Az-Zalzalah","الزلزلة","The Earthquake",8,"medinan",[30]),
(100,"Al-'Adiyat","العاديات","The Courser",11,"meccan",[30]),
(101,"Al-Qari'ah","القارعة","The Calamity",11,"meccan",[30]),
(102,"At-Takathur","التكاثر","The Rivalry in World Increase",8,"meccan",[30]),
(103,"Al-'Asr","العصر","The Declining Day",3,"meccan",[30]),
(104,"Al-Humazah","الهمزة","The Traducer",9,"meccan",[30]),
(105,"Al-Fil","الفيل","The Elephant",5,"meccan",[30]),
(106,"Quraysh","قريش","Quraysh",4,"meccan",[30]),
(107,"Al-Ma'un","الماعون","The Small Kindnesses",7,"meccan",[30]),
(108,"Al-Kawthar","الكوثر","The Abundance",3,"meccan",[30]),
(109,"Al-Kafirun","الكافرون","The Disbelievers",6,"meccan",[30]),
(110,"An-Nasr","النصر","The Divine Support",3,"medinan",[30]),
(111,"Al-Masad","المسد","The Palm Fiber",5,"meccan",[30]),
(112,"Al-Ikhlas","الإخلاص","The Sincerity",4,"meccan",[30]),
(113,"Al-Falaq","الفلق","The Daybreak",5,"meccan",[30]),
(114,"An-Nas","الناس","Mankind",6,"meccan",[30]),
]

assert len(rows) == 114, f"expected 114 rows, got {len(rows)}"
total_ayahs = sum(r[4] for r in rows)
print("total ayahs:", total_ayahs)

surahs = [
    {
        "number": r[0],
        "name": r[1],
        "arabicName": r[2],
        "englishTranslation": r[3],
        "ayahCount": r[4],
        "revelationType": r[5],
        "juz": r[6],
    }
    for r in rows
]

with open("/home/claude/hifzai/src/data/surahs.json", "w", encoding="utf-8") as f:
    json.dump(surahs, f, ensure_ascii=False, indent=2)
    f.write("\n")

print("wrote", len(surahs), "surahs")
